config/routes.rb
Rails.application.routes.draw do
  get 'drafts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, skip: [:registrations]
  ActiveAdmin.routes(self)
  
  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  authenticated :user do
    resource :my_picks, only: :show
    
    # root "seasons#show_active_season"
    resources :leagues do
      resource :draft, only: :show
    end
    root "leagues#latest_league"
  end
  resource :all_picks, only: :show
  resources :picks, only: [:update] do 
    resource :lock
  end

  resources :seasons do 
    resources :season_lines, only: [:index]
  end

end

#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                               admin_root GET    /admin(.:format)                                                                                  admin/dashboard#index
#                          admin_dashboard GET    /admin/dashboard(.:format)                                                                        admin/dashboard#index
#            enroll_all_users_admin_league POST   /admin/leagues/:id/enroll_all_users(.:format)                                                     admin/leagues#enroll_all_users
#                 build_draft_admin_league POST   /admin/leagues/:id/build_draft(.:format)                                                          admin/leagues#build_draft
#               batch_action_admin_leagues POST   /admin/leagues/batch_action(.:format)                                                             admin/leagues#batch_action
#                            admin_leagues GET    /admin/leagues(.:format)                                                                          admin/leagues#index
#                                          POST   /admin/leagues(.:format)                                                                          admin/leagues#create
#                         new_admin_league GET    /admin/leagues/new(.:format)                                                                      admin/leagues#new
#                        edit_admin_league GET    /admin/leagues/:id/edit(.:format)                                                                 admin/leagues#edit
#                             admin_league GET    /admin/leagues/:id(.:format)                                                                      admin/leagues#show
#                                          PATCH  /admin/leagues/:id(.:format)                                                                      admin/leagues#update
#                                          PUT    /admin/leagues/:id(.:format)                                                                      admin/leagues#update
#                                          DELETE /admin/leagues/:id(.:format)                                                                      admin/leagues#destroy
#                 batch_action_admin_picks POST   /admin/picks/batch_action(.:format)                                                               admin/picks#batch_action
#                              admin_picks GET    /admin/picks(.:format)                                                                            admin/picks#index
#                                          POST   /admin/picks(.:format)                                                                            admin/picks#create
#                           new_admin_pick GET    /admin/picks/new(.:format)                                                                        admin/picks#new
#                          edit_admin_pick GET    /admin/picks/:id/edit(.:format)                                                                   admin/picks#edit
#                               admin_pick GET    /admin/picks/:id(.:format)                                                                        admin/picks#show
#                                          PATCH  /admin/picks/:id(.:format)                                                                        admin/picks#update
#                                          PUT    /admin/picks/:id(.:format)                                                                        admin/picks#update
#                                          DELETE /admin/picks/:id(.:format)                                                                        admin/picks#destroy
#          batch_action_admin_season_lines POST   /admin/season_lines/batch_action(.:format)                                                        admin/season_lines#batch_action
#                       admin_season_lines GET    /admin/season_lines(.:format)                                                                     admin/season_lines#index
#                                          POST   /admin/season_lines(.:format)                                                                     admin/season_lines#create
#                    new_admin_season_line GET    /admin/season_lines/new(.:format)                                                                 admin/season_lines#new
#                   edit_admin_season_line GET    /admin/season_lines/:id/edit(.:format)                                                            admin/season_lines#edit
#                        admin_season_line GET    /admin/season_lines/:id(.:format)                                                                 admin/season_lines#show
#                                          PATCH  /admin/season_lines/:id(.:format)                                                                 admin/season_lines#update
#                                          PUT    /admin/season_lines/:id(.:format)                                                                 admin/season_lines#update
#                                          DELETE /admin/season_lines/:id(.:format)                                                                 admin/season_lines#destroy
#               batch_action_admin_seasons POST   /admin/seasons/batch_action(.:format)                                                             admin/seasons#batch_action
#                            admin_seasons GET    /admin/seasons(.:format)                                                                          admin/seasons#index
#                                          POST   /admin/seasons(.:format)                                                                          admin/seasons#create
#                         new_admin_season GET    /admin/seasons/new(.:format)                                                                      admin/seasons#new
#                        edit_admin_season GET    /admin/seasons/:id/edit(.:format)                                                                 admin/seasons#edit
#                             admin_season GET    /admin/seasons/:id(.:format)                                                                      admin/seasons#show
#                                          PATCH  /admin/seasons/:id(.:format)                                                                      admin/seasons#update
#                                          PUT    /admin/seasons/:id(.:format)                                                                      admin/seasons#update
#                                          DELETE /admin/seasons/:id(.:format)                                                                      admin/seasons#destroy
#                 batch_action_admin_users POST   /admin/users/batch_action(.:format)                                                               admin/users#batch_action
#                              admin_users GET    /admin/users(.:format)                                                                            admin/users#index
#                                          POST   /admin/users(.:format)                                                                            admin/users#create
#                           new_admin_user GET    /admin/users/new(.:format)                                                                        admin/users#new
#                          edit_admin_user GET    /admin/users/:id/edit(.:format)                                                                   admin/users#edit
#                               admin_user GET    /admin/users/:id(.:format)                                                                        admin/users#show
#                                          PATCH  /admin/users/:id(.:format)                                                                        admin/users#update
#                                          PUT    /admin/users/:id(.:format)                                                                        admin/users#update
#                                          DELETE /admin/users/:id(.:format)                                                                        admin/users#destroy
#                           admin_comments GET    /admin/comments(.:format)                                                                         admin/comments#index
#                                          POST   /admin/comments(.:format)                                                                         admin/comments#create
#                            admin_comment GET    /admin/comments/:id(.:format)                                                                     admin/comments#show
#                                          DELETE /admin/comments/:id(.:format)                                                                     admin/comments#destroy

app/models/pick.rb
# == Schema Information
#
# Table name: picks
#
#  id             :bigint           not null, primary key
#  over           :boolean
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  enrollment_id  :bigint
#  season_line_id :bigint
#
# Indexes
#
#  index_picks_on_enrollment_id                     (enrollment_id)
#  index_picks_on_season_line_id                    (season_line_id)
#  index_picks_on_season_line_id_and_enrollment_id  (season_line_id,enrollment_id) UNIQUE
#

class Pick < ApplicationRecord
  has_one :lock, dependent: :destroy
  belongs_to :enrollment
  belongs_to :season_line
  has_one  :season, through: :enrollment
  has_one  :team, through: :season_line
  has_one  :user, through: :enrollment
  has_one  :league, through: :enrollment

  after_update :update_season_channel
  after_touch :update_season_channel

  validates_uniqueness_of :season_line, scope: :enrollment

  accepts_nested_attributes_for :lock

  def score
    if over == season_line.over?
      locked? ? (ENV['PICK_CORRECT_LOCKED'] || Rails.application.credentials[:PICK_CORRECT_LOCKED]).to_i : (ENV['PICK_CORRECT'] || Rails.application.credentials[:PICK_CORRECT]).to_i
    elsif lock
      (ENV['PICK_INCORRECT_LOCKED'] || Rails.application.credentials[:PICK_INCORRECT_LOCKED]).to_i
    else
      (ENV['PICK_INCORRECT'] || Rails.application.credentials[:PICK_INCORRECT]).to_i
    end
  end

  def correct?
    return if over.nil?
    over && season_line.over? || !over && !season_line.over?
  end

  def team_name
    team.name
  end

  def team_city
    team.city
  end

  def locked?
    !lock.nil? && lock.persisted?
  end

  def update_season_channel
    pick = ApplicationController.render(
      partial: 'picks/pick',
      locals: { pick: self }
    )
    ActionCable.server.broadcast "season_channel_#{season.id}", { pick: pick, pickId: id }
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :set_pick, only: :update

  def index
    @user = User.find_by_email('logandsprice@gmail.com')
    @picks = @user.picks.includes(:season_line, :team).joins(:team).merge(Team.order(name: :asc))

    teams_by_conference = Team.all.group_by { |team| team.conference }
    @teams_by_division = teams_by_conference.transform_values { |teams| teams.group_by { |team| team.division } }
  end

  def update
    puts '*' * 60
    puts 'In Picks#update!'
    puts '*' * 60
    
    # error clause for if it fails to update
    
    return unless @pick.league.drafting_enabled?
    @pick.reload unless @pick.update(pick_params)
    

  end

  private

  def set_pick
    @pick = Pick.find(params[:id])
  end
  
  def pick_params
    @pick_params ||= params.require(:pick).permit!
  end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_form.html.erb
<%= form_with(model: pick, local: true) do |form| %>
  <% if pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
      <% pick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contestant_id %>
    <%= form.number_field :contestant_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :over %>
    <%= form.check_box :over %>
  </div>

  <div class="field">
    <%= form.label :lock %>
    <%= form.check_box :lock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/picks/_over_under_buttons.html.erb
<div class="row flex-grow-1">
  <div class="col-6">
    <%= form_with(model: pick, local: false, class: "d-flex align-items-center") do |f| %>
      <% button_classes = ["btn btn-lg col-12"] %>
      <% button_classes << (f.object.over == true ? "btn-success disabled" : "btn-outline-success")%>
      <%= f.hidden_field :over, value: true %>
      <%= f.submit "OVER", class: button_classes.join(" ") %>
    <% end %>
  </div>
  <div class="col-6">
    <%= form_with(model: pick, local: false, class: "d-flex align-items-center") do |f| %>
      <% button_classes = ["btn btn-lg col-12"] %>
      <% button_classes << (f.object.over == false ? "btn-danger disabled" : "btn-outline-danger")%>
      <%= f.hidden_field :over, value: false %>
      <%= f.submit "UNDER", class: button_classes.join(" ") %>
    <% end %>
  </div>
</div>

app/views/picks/_pick.html.erb
<div class="col d-flex flex-column" id="<%= dom_id(pick) %>" >
  <%# div_ordering = pick.over ? { pick: 1, result_icon: 2 } : { pick: 2, result_icon: 1 } %>
  <% div_ordering = { pick: 1, result_icon: 2 } %>
  <div class="row order-<%= div_ordering[:pick] %>">
    <div class="col m-1 p-0 ratio ratio-1x1 ">
      <% vertical_alignment = { true => "start", false => "end", nil => "center"}[pick.over] %>
      <% cell_classes = [
        "d-flex",
        "justify-content-center",
        "align-items-center",
        "border",
        "border-3",
        "border-dark",
      ] %>
      <% icon_classes_hash = { true => "fas fa-3x fa-chevron-double-up", false => " fas fa-3x fa-chevron-double-down", nil => "fal fa-3x fa-question" } %>
      <% icon_classes = icon_classes_hash[pick.over] + (pick.correct? ? " text-success" : " text-danger") %>
      <div class="<%= cell_classes.join(" ") %>" style="border-radius: 15px;">
        <i class="<%= icon_classes %> "></i>
      </div>
    </div>
  </div>
  <div class="row order-<%= div_ordering[:result_icon] %>">
    <div class="col-6 fs-4 d-flex justify-content-center">
      <% score = pick.score %>
      <% modifier = "+" if score.positive? %>
      <%= "#{ modifier }#{pick.score}" %>

  
    </div>
    <div class="col-6">
        <% if pick.locked? %>
          <div class="text-warning">
            <%= fa_icon("fad 2x lock-alt") %>
          </div>
        <% end %>
      
    </div>
  </div>
</div>

app/views/picks/_pick_forms.html.erb
<div class="row" id="pick_<%= pick.id %>_forms">
  <div class="offset-2 col-3">
    <div class="row">
      <% season_line = pick.season_line %>
      <%= render partial: "/shared/team_info", locals: { season_line: season_line, omit_pace: (omit_pace || false) } %>
    </div>
  </div>
  <div class="col-3 d-flex align-items-center ">
    <%= render partial: "/picks/over_under_buttons", locals: { pick: pick } %>
  </div>
  <div class="col-3 d-flex align-items-center">
    
        <% lock = pick.lock || pick.build_lock %>
        <%= render lock, pick: pick %>
  </div>
</div>

app/views/picks/edit.html.erb
<h1>Editing Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Show', @pick %> |
<%= link_to 'Back', picks_path %>

app/views/picks/index.html.erb
<div class="header"></div>
<table class="table">
  <tr>
    <th>Conference</th>
    <th>Division</th>
    <th>Team</th>
    <th>Line</th>
    <th>Over?</th>
    <th>Locked?</th>
  </tr>
  <% @teams_by_division.each do |conference, division_hash| %>
    <tr>
      <td colspan="6">
        <%= conference %>
      </td>
    </tr>
    <% division_hash.each do |division_name, division_teams| %>
      <tr>
        <td></td>
        <td colspan="5">
          <%= division_name %>
        </td>
      </tr>
      <%= render partial: "pick_forms", collection: @picks.where(teams: {id: division_teams.map(&:id)}), as: :pick %>
    <% end %>
  <% end %>
</table>

app/views/picks/new.html.erb
<h1>New Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Back', picks_path %>

app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contestant:</strong>
  <%= @pick.contestant_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @pick.team_id %>
</p>

<p>
  <strong>Over:</strong>
  <%= @pick.over %>
</p>

<p>
  <strong>Lock:</strong>
  <%= @pick.lock %>
</p>

<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>

app/views/picks/update.js.erb
$("#pick_<%= @pick.id %>_forms").replaceWith("<%= j render partial: "pick_forms", locals: { pick: @pick, omit_pace: true } %>");