config/routes.rb
Rails.application.routes.draw do
  get 'drafts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, skip: [:registrations]
  ActiveAdmin.routes(self)
  
  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  authenticated :user do
    resource :my_picks, only: :show
    
    # root "seasons#show_active_season"
    resources :leagues do
      resource :draft, only: :show
    end
    root "leagues#latest_league"
  end
  resource :all_picks, only: :show
  resources :picks, only: [:update] do 
    resource :lock
  end

  resources :seasons do 
    resources :season_lines, only: [:index]
  end

end

#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                               admin_root GET    /admin(.:format)                                                                                  admin/dashboard#index
#                          admin_dashboard GET    /admin/dashboard(.:format)                                                                        admin/dashboard#index
#            enroll_all_users_admin_league POST   /admin/leagues/:id/enroll_all_users(.:format)                                                     admin/leagues#enroll_all_users
#                 build_draft_admin_league POST   /admin/leagues/:id/build_draft(.:format)                                                          admin/leagues#build_draft
#               batch_action_admin_leagues POST   /admin/leagues/batch_action(.:format)                                                             admin/leagues#batch_action
#                            admin_leagues GET    /admin/leagues(.:format)                                                                          admin/leagues#index
#                                          POST   /admin/leagues(.:format)                                                                          admin/leagues#create
#                         new_admin_league GET    /admin/leagues/new(.:format)                                                                      admin/leagues#new
#                        edit_admin_league GET    /admin/leagues/:id/edit(.:format)                                                                 admin/leagues#edit
#                             admin_league GET    /admin/leagues/:id(.:format)                                                                      admin/leagues#show
#                                          PATCH  /admin/leagues/:id(.:format)                                                                      admin/leagues#update
#                                          PUT    /admin/leagues/:id(.:format)                                                                      admin/leagues#update
#                                          DELETE /admin/leagues/:id(.:format)                                                                      admin/leagues#destroy
#                 batch_action_admin_picks POST   /admin/picks/batch_action(.:format)                                                               admin/picks#batch_action
#                              admin_picks GET    /admin/picks(.:format)                                                                            admin/picks#index
#                                          POST   /admin/picks(.:format)                                                                            admin/picks#create
#                           new_admin_pick GET    /admin/picks/new(.:format)                                                                        admin/picks#new
#                          edit_admin_pick GET    /admin/picks/:id/edit(.:format)                                                                   admin/picks#edit
#                               admin_pick GET    /admin/picks/:id(.:format)                                                                        admin/picks#show
#                                          PATCH  /admin/picks/:id(.:format)                                                                        admin/picks#update
#                                          PUT    /admin/picks/:id(.:format)                                                                        admin/picks#update
#                                          DELETE /admin/picks/:id(.:format)                                                                        admin/picks#destroy
#          batch_action_admin_season_lines POST   /admin/season_lines/batch_action(.:format)                                                        admin/season_lines#batch_action
#                       admin_season_lines GET    /admin/season_lines(.:format)                                                                     admin/season_lines#index
#                                          POST   /admin/season_lines(.:format)                                                                     admin/season_lines#create
#                    new_admin_season_line GET    /admin/season_lines/new(.:format)                                                                 admin/season_lines#new
#                   edit_admin_season_line GET    /admin/season_lines/:id/edit(.:format)                                                            admin/season_lines#edit
#                        admin_season_line GET    /admin/season_lines/:id(.:format)                                                                 admin/season_lines#show
#                                          PATCH  /admin/season_lines/:id(.:format)                                                                 admin/season_lines#update
#                                          PUT    /admin/season_lines/:id(.:format)                                                                 admin/season_lines#update
#                                          DELETE /admin/season_lines/:id(.:format)                                                                 admin/season_lines#destroy
#               batch_action_admin_seasons POST   /admin/seasons/batch_action(.:format)                                                             admin/seasons#batch_action
#                            admin_seasons GET    /admin/seasons(.:format)                                                                          admin/seasons#index
#                                          POST   /admin/seasons(.:format)                                                                          admin/seasons#create
#                         new_admin_season GET    /admin/seasons/new(.:format)                                                                      admin/seasons#new
#                        edit_admin_season GET    /admin/seasons/:id/edit(.:format)                                                                 admin/seasons#edit
#                             admin_season GET    /admin/seasons/:id(.:format)                                                                      admin/seasons#show
#                                          PATCH  /admin/seasons/:id(.:format)                                                                      admin/seasons#update
#                                          PUT    /admin/seasons/:id(.:format)                                                                      admin/seasons#update
#                                          DELETE /admin/seasons/:id(.:format)                                                                      admin/seasons#destroy
#                 batch_action_admin_users POST   /admin/users/batch_action(.:format)                                                               admin/users#batch_action
#                              admin_users GET    /admin/users(.:format)                                                                            admin/users#index
#                                          POST   /admin/users(.:format)                                                                            admin/users#create
#                           new_admin_user GET    /admin/users/new(.:format)                                                                        admin/users#new
#                          edit_admin_user GET    /admin/users/:id/edit(.:format)                                                                   admin/users#edit
#                               admin_user GET    /admin/users/:id(.:format)                                                                        admin/users#show
#                                          PATCH  /admin/users/:id(.:format)                                                                        admin/users#update
#                                          PUT    /admin/users/:id(.:format)                                                                        admin/users#update
#                                          DELETE /admin/users/:id(.:format)                                                                        admin/users#destroy
#                           admin_comments GET    /admin/comments(.:format)                                                                         admin/comments#index
#                                          POST   /admin/comments(.:format)                                                                         admin/comments#create
#                            admin_comment GET    /admin/comments/:id(.:format)                                                                     admin/comments#show
#                                          DELETE /admin/comments/:id(.:format)                                                                     admin/comments#destroy

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaOverUnder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://kit.fontawesome.com/9091341b10.js" %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="row">
          <div class="col-6">
            <div class="row d-flex align-items-center">
              <div class="col-1">
                <a href="/">
                  <%= image_tag "https://pngimg.com/uploads/nba/nba_PNG20.png", class: "img-fluid" %>
                </a>
              </div>
              <div class="col-11">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="navbar-brand nav-link" href="#">Over/Under Madness</a>
                    </li>
                    <% if current_user %>
                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Season Overview</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/my_picks">My Picks</a>
                      </li>
                      <li class="nav-item">
                        <%= link_to "Draft", league_draft_path(current_league), class: "nav-link" %>
                      </li>
                    <% end%>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <%= content_tag("p", class: "notice") { notice } if notice %>
        <%= content_tag("p", class: "alert") { alert } if alert %>
        <div class="col-sm-12">
          <%= yield %>
          <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% end%>
        </div>
      </div>
    </div>
  </body>
</html>